---
apiVersion: v1
kind: Pod
metadata:
  name: time-check
  namespace: nautilus
spec:
  containers:
  - name: time-check
    image: busybox:latest
    command: ["/bin/sh"]
    args: ["-c", "while true; do date; sleep $TIME_FREQ;done > /opt/itadmin/time/time-check.log"]
    env:
        - name: TIME_FREQ
          valueFrom:            configMapKeyRef:
              name: time-config
              # Specify the key associated with the value
              key: TIME_FREQ
    volumeMounts:
        - name: log-volume
          mountPath: /opt/itadmin/time
  volumes:
    - name: log-volume
      emptyDir: {}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: time-config
  namespace: nautilus
data:
  TIME_FREQ: ‘6’
---
apiVersion: v1
kind: Namespace
metadata:
  name: nautilus
